FORMAT: 1A
HOST: pokemasters.me

# pokemonproject

Pokemon API for looking up information on Pokemon, moves, and locations.

## Pokemon Collection [/api/v1.0/pokemon]

A list of all pokemon

### List All Pokemon [GET]
  
+ Response 200 (application/json)
    
        [
            {
                "id": 1,
                "name": "Bulbasaur"
            },
            {
                "etc..."
            }
        ]

## Pokemon [/api/v1.0/pokemon/{id}]
A single pokemon with id provided.

### View Pokemon [GET]

+ Parameters
    + id: None(required, number) - Needed to get unique pokemon.

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Bulbasaur"
        }

+ Response 404 (application/json)

        {
            "error":"No pokemon here"
        }

## Move Collection [/api/v1.0/moves]
A list of all moves

### List All Moves [GET]

+ Response 200 (application/json)

         [
            {
                "id": 1,
                "name": "Rain-dance"
            },
            {
                "etc..."
            }
        ]
        
## Move [/api/v1.0/moves/{id}]
A single move associated with this id
        
### View Move [GET]

+ Parameters
    + id: None(required, number) - ID of unique move.
    
+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Rain-dance"
        }

## Location Collection [/api/v1.0/location]
A list of all locations

### List All Locations [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1,
                "generation": "1"
            },
            {
                "etc..."
            }
        ]
        
## Location [/api/v1.0/location/{id}]
A single location at route id

### View Location [GET]

+ Parameters
    + id: None(required, number) - ID of unique location of a certain generation.
    
+ Response 200 (application/json)

        {
            "id": 1,
            "generation": "1"
        }

        
        
        
        
        
        
        
            
        
        
        
        
        
        
